# **Pengantar**

Python is an object-oriented language that was developed in late 1980s as a scripting language (the name is derived from the British television show Monty Python’s Flying Circus).
Python has other advantages over mainstream languages that are important in a learning environment:
*   Python is open-source software, which means that it is free; it is included in most Linux distributions.
*   Python is available for all major operating systems (Linux, Unix, Windows, Mac OS etc.). A program written on one system runs without modification on all systems.
*   Python is easier to learn and produces more readable code than other languages.
*   Python and its extensions are easy to install.






#**Eksplorasi Code Program berikut!**
Berikan komentar (#komentar) pada bagian-bagian yang menurut anda penting!

**Variabel**

In [1]:
b=2 #Deklarasikan variabel dan nilainya
print(b) #Print nilai variabel b

2


In [ ]:
b=b*2.0 
print(b)

4.0


**String**

In [ ]:
string1 = 'Press return to exit' #Deklarasikan variabel dengan tipe data string
string2 = 'the program' #Deklarasikan variabel dengan tipe data string
print(string1) #Print hasil string1
print(string2) #Print hasil string2
print(string1 ,'',string2) #print hasil program string1 dan string2
print(string1[0:12]) #print hasil string1 sampai 12 char

Press return to exit
the program
Press return to exit  the program
Press return


**Tuples**

In [ ]:
rec = ('Junaeti','Enjun',(12,20,1985)) #Deklarasikan variabel untuk menampung sekumpulan data
lastName, firstName, birthdate = rec #Deklarasikan variabel 
print(rec[0]) #menampilkan hasil 
print(lastName) #menampilkan hasil 
nama = rec[1] + ' ' + rec[0] #Deklarasikan variabel 
print(nama) #menampilkan hasil 
birtYear = birthdate[2] #membuat variabel tampungan
print(birthdate) #menampilkan hasil

Junaeti
Junaeti
Enjun Junaeti
(12, 20, 1985)


**List**

In [ ]:
a = [1.0, 2.0, 3.0] #deklarasikan variabel
a.append(4.0) #menambahkan nilai array pada urutan terakhir
print(a) #menampilkan hasil
a.insert(0,0.0) #menyisipkan data pada urutan pertama
print(a) #menampilkan hasil
print (len(a)) #menampilkan panjang array a
a[2:4] = [1.0, 1.0]
print(a)  

[1.0, 2.0, 3.0, 4.0]
[0.0, 1.0, 2.0, 3.0, 4.0]
5
[0.0, 1.0, 1.0, 1.0, 4.0]


In [ ]:
a = [1.0, 2.0, 3.0]
b=a
b[0] = 5.0
print (a)


[5.0, 2.0, 3.0]


In [ ]:
a = [5.0, 2.0, 3.0]
c = a[:] 
c[0]=1.0
print(a)

[5.0, 2.0, 3.0]


**Matriks**

In [ ]:
A =[[1, 2, 3], \ #mendeklarasikan matriks
[4, 5, 6], \
[7, 8, 9]]
print(A[1]) #menampilkan hasil
print(A[1][2])

[4, 5, 6]
6


**Operasi Aritmatika**

In [ ]:
s = 'Hello' #mendeklarasikan variabel
t = 'to you' #mendeklarasikan variabel
a = [1, 2, 3] #mendeklarasikan variabel
print (3*s) #menampilkan hasil
print (3*a) 
print (a + [4, 5]) 
print(s+t) 
print(s+' '+t)

HelloHelloHello
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5]
Helloto you
Hello to you


In [ ]:
a=2
b=3
a+=b
print(a)
a-=b
print(a)
a*=b
print(a)
a/=b
print(a)
a**=b
print(a)
a%=b
print(a)

5
2
6
2.0
8.0
2.0


**Operator Perbandingan**

In [ ]:
a = 2 #mendeklarasikan variabel
b = 1.99 
c = '2'
print(a>b) #menampilkan hasil
print (a == c)
print (a > b) and (a != c)
print (a > b) or (a == b)


True
False
True
True


False

**Percabangan**

In [ ]:
def sign_of_a(a): #mendefinikan fungsi
  if a < 0.0: #melakukan percabangan
    sign = 'negative'
  elif a > 0.0:
    sign = 'positive'
  else:
    sign = 'zero'
  return sign
a = 1.5
print ('a is ' + sign_of_a(a)) #menampilkan hasil

a is positive


**Loops**

In [ ]:
nMax = 5
n=1
a = [] # membuat list kosong
while n < nMax:
  a.append(1.0/n) #menambahkan elemen dalam list
  n=n+1
print (a)

[1.0, 0.5, 0.3333333333333333, 0.25]


In [ ]:
nMax = 5
a=[]
for n in range(1,nMax):
  a.append(1.0/n)
print (a)

[1.0, 0.5, 0.3333333333333333, 0.25]


In [ ]:
list = ['Jack', 'Jill', 'Tim', 'Dave']
name = input('Type a name: ') # Python input prompt
for i in range(len(list)):
  if list[i] == name:
    print (name,'is number',i + 1,'on the list')
    break
else:
  print (name,'is not on the list')

Type a name: Jee
Jee is not on the list


**Fungsi**

In [ ]:
def squares(a): #mendefinikan fungsi
  for i in range(len(a)): #melakukan perulangan
    a[i]**=2
a = [1, 2, 3, 4]
squares(a)
print (a) 

[1, 4, 9, 16]


**math Module**

In [ ]:
from math import log,sin #import library
print(log(10))
print(sin(0.5))

2.302585092994046
0.479425538604203


In [ ]:
import math
print(math.log(10))

2.302585092994046


**Array**

In [ ]:
import numpy as np #import library
b = [1.0, 4.0, 2.0]
print(np.dot(b,b))
a = [[ 4.0, -2.0, 1.0], \
[-2.0, 4.0, -2.0], \
[ 1.0, -2.0, 3.0]]
print(np.dot(a,b))

21.0
[-2. 10. -1.]


# **Latihan**

**Eksplorasi kode program berikut dengan memberikan keterangan pada setiap tahapannya!**

In [ ]:
import numpy as np #import library numpy
def my_bisection(g, a, b, e): #mendefinisikan fungsi
  if np.sign(g(a)) == np.sign(g(b)): #mengecek kondisi
    raise Exception('Tidak ada akar pada interval a dan b') 
  m = (a + b)/2
  if np.abs(g(m)) < e: #mengecek kondisi
    return m #menampilkan hasil
  elif np.sign(g(a)) == np.sign(g(m)): #mengecek kondisi
    return my_bisection(g, m, b, e) #menampilkan hasil
  elif np.sign(g(b)) == np.sign(g(m)): #mengecek kondisi
    return my_bisection(g, a, m, e) #menampilkan hasil

**Buatlah Kode Program berikut ini!**

In [2]:
from re import X
# Definisikan suatu matriks A berordo 2x3 dengan entri-entri yang ditentukan sendiri
A = [[4,5,6], [7,8,9]]

# Definisikan suatu matriks B berordo 3x3 dengan entri-entri yang ditentukan sendiri
B = [[4,5,6], [7,8,9], [10,11,12]]

# Definisikan suatu matriks C berordo 3x2 dengan entri-entri yang ditentukan sendiri
C = [[3,4], [5,6], [7,8]]

# Carilah perkalian matriks A dan B kemudian print hasilnya
import numpy as np
x = np.dot(A,B)
print(x)

# Carilah perkalian matriks B dan C kemudian print hasilnya
y = np.dot(B,C)
print(y)

# Carilah perkalian matriks C dan A kemudian print hasilnya
y = np.dot(C,A)
print(y)

[[111 126 141]
 [174 198 222]]
[[ 79  94]
 [124 148]
 [169 202]]
[[ 40  47  54]
 [ 62  73  84]
 [ 84  99 114]]


In [3]:
#Yeni Isnaeni 2007897 Pendidikan Ilmu Komputer B
#Mata Kuliah : Metode Numerik

import numpy as np

#Menampilkan Matriks A dan Matriks B
string1 = 'Matriks A'
A = [[1, 2, 0], \
     [2, 2, 1], \
     [0, 3, 3]]
print(string1)
print(A)

string2 = '\nMatriks B'
B = [[-1, 5], \
     [ 3, 1], \
     [ 0, 1]]
print(string2)
print(B)

transposeA = np.transpose(A)
transposeB = np.transpose(B)

#Menjumlahkan Matriks A dan B
string3 = '\nPenjumlahan Matriks A dan B'
print(string3)
if len(A) == len(B) :
  if len(transposeA) == len(transposeB) :
    for x in range(0, len(A)):
      for y in range(0, len(B[0])):
        print (A[x][y] + B[x][y], end=' '),
      print (" ")
  else:
    print('Matriks tidak dapat dijumlahkan karena mempunyai ordo yang berbeda')
else:
    print('Matriks tidak dapat dijumlahkan karena mempunyai ordo yang berbeda')

#Mengalikan Matriks A dan B
string4 = '\nPerkalian Matriks A dan B'
print(string4)
print(np.dot(A,B))


Matriks A
[[1, 2, 0], [2, 2, 1], [0, 3, 3]]

Matriks B
[[-1, 5], [3, 1], [0, 1]]

Penjumlahan Matriks A dan B
Matriks tidak dapat dijumlahkan karena mempunyai ordo yang berbeda

Perkalian Matriks A dan B
[[ 5  7]
 [ 4 13]
 [ 9  6]]
